### ISSUE TITLE
Comparisons: Modeling Hierarchy

### ISSUE THREAD

**Issue by ormsbee** [open-craft/blockstore#26]
@bradenmacdonald, @symbolist, @pdpinch:

This is a spinoff of #16, where we can dive more into hierarchy modeling specifically. I’m trying to be even handed in my analysis, but I obviously have both an imperfect understanding of the proposals on the table as well as a personal preference, so please treat this issue description like a wiki and edit it until you feel it fairly represents the tradeoffs.

The proposals on the table are:
* Bundle Per Block (BPB)
* Hierarchical One Bundle Course (HOBC)
* Flat One Bundle Course (FOBC)
* Course Bundle, Unit Bundle (CBUB)

BPB and HOBC treat hierarchy modeling as a Blockstore primitive. BPB does this by narrowing the scope of a Bundle to only cover single Blocks, and leaning on our more-or-less original formulation of BundleVersion Links to string things together. HOBC uses a combination of file system conventions and a new Folder primitive that provides a more nuanced version of Links that allows for version-relative linking. FOBC and CBUB punt hierarchy modeling responsibility entirely to systems outside Blockstore, by storing the OLX for those relationships but not having any built-in understanding of how those relationships work.

Some of the driving use cases here:
* Re-use of non-leaf blocks like Units.
* Granular course publishing (at course, chapter, sequence, unit, and possibly even individual leaf levels)
* Adaptive use cases calling for a more flexible/dynamic traversal of content.
* Remixing of larger content that lives primarily in a course (e.g. a sequence).
* Potentially restructuring existing Course Content (CCX example)

Of those, the first one is providing the strongest push to model hierarchy explicitly.

## Bundle Per Block (BPB)

BPB’s core strength is that is is both conceptually simple and highly flexible. It can represent anything the other two can and its concept of Links is more straightforward than HOBC Folders since it’s just a M:M relationship between BundleVersions. There is a bit more complexity in grouping commits together logically (four Bundles changing could be the result of one meaningful edit), but that can be accommodated by modeling those commits as first class entities of their own and having a 1:M relationship with the created BundleVersions.

The main drawbacks of BPB are operational. Import operations could potentially affect thousands of separately committed Bundles that need to be updated together in a transaction. Simple updates to leaf nodes would require chained BundleVersion creation. The proliferation of BundleVersions and M:M relationships are a longer term scaling concern, particularly in the absence of a native graph database that can efficiently store and traverse such relationships—though using such a database would present other operational concerns since it would require moving away from our more established stack. The ratio of metadata to actual data is also potentially high, since we need to create a Bundle, a BundleVersion and any associated relationship metadata for leaf node that might just amount to a single tag with an attribute. This is less a storage concern than it is a "how many rows do we need to write and read from the database" concern.

It’s possible that these issues can be mitigated through more efficient representations, though there’s another tradeoff there in that such representations tend to add runtime complexity and read performance penalties.

## Hierarchical One Bundle Course (HOBC)

HOBC attempts to maintain some of the simplicity of BPB while greatly reducing the operational complexity through the introduction of an additional primitive. Like BPB, there is one primitive that represents most things in the system: a "Folder" can represent a course, section, subsection, unit, XBlock, pathway, program, etc. Unlike BPB however, this smallest primitive is not versioned on its own.

The primitives become:
* Collection - holds ownership, licensing, permission, and other metadata for a set of things with a common author
* Bundle - a versioned container of typed folders. Container for all the data for a Course, Problem Bank, Content Library, Pathway, or Program.
* Folder - a "thing" that belongs to a Bundle. Examples: a course outline, an XBlock, a section, a subsection, or a unit. A folder is owned by one bundle but may appear in other bundles.

The key difference is that when Folders refer to other Folders within the same Bundle (for example, a Unit folder declares that it is comprised of several specific XBlock Folders), it is an unversioned reference. So for example, when importing a course with 1,000 XBlocks, only a single new BundleVersion is created (whereas BPB would create 1,000+ BundleVersions that can be linked to independently).

The advantages of this model are that the representation of a single typical course is very operationally efficient, and that content reuse can happen at any granularity - XBlock, unit, subsection, section, course, or pathway. 

One significant shortcoming of HOBC is that determining the entire course hierarchy/outline requires reading many different files from many different folders (read sections from course.json in the course folder, then read each section's section.xml from each section's folder, then read each subsection's subsection.xml from each subsection's folder, and so on...)

## Flat One Bundle Course (FOBC)

The main focus of FOBC is implementation and operational simplicity, and so it takes the view that the storage layer of Blockstore shouldn’t try to model hierarchical relationships at all. A student’s path through a course is an LMS/Compositor level concern that structural OLX is an input to, and it’s better to do nothing than to add complexity to build a limiting version of this at this layer.

The major drawback of this is that FOBC requires more explicit intentionality in course design in order for its BundleVersion dependency tracking to be meaningful. You could borrow a single leaf block or container block from another Course, but Blockstore itself would only know that the link between the BundleVersions existed, not the specific items that were used. For that reason, a problem in a problem bank would be modeled as its own Bundle. Getting more precision than that would require building a separate, OLX-aware system to track re-use in a richer way.

Another drawback is that the Snapshot representation for large courses would be relatively large for our big outlier courses, and we’d be creating a new one on every publish. This doesn’t hit us much in costs (our worst case is still in the neighborhood of $0.20 a month), but it can make traversals of the full set of snapshots relatively expensive.

Similarly to HOBC, finding the course outline requires multiple roundtrips and many reads on large courses.

## Course Bundle, Unit Bundle (CBUB)

The Course Bundle, Unit Bundle proposal is that courses (and libraries, and pathways) are represented as a single bundle containing an `outline.xml` file which describes the entire course structure (sections, subsections, and Units) along with a list of all the versioned leaf node ([Unit XBlock](https://github.com/open-craft/unit-xblock/)) bundles that are used in the course. (So Units and Courses get their own bundle, but intermediate hierarchical elements like section and subsection are not represented as bundles.)

Units are composable up to some small limit, so a unit may contain a unit as a child, though when rendered in the LMS the result is flattened (i.e. the users would not see that hierarchy represented in the UI). An OLX convention/mechanism would allow for courses, pathways, units, etc. to link to a unit but only use one of the XBlocks within that unit rather than the whole unit.

Some advantages of this proposal are:
* It's extremely simple
* Reading the full outline of a course is very fast and easy (read one file)
* Separation of concerns: Blockstore doesn't know anything about course hierarchy
* Reasonable operational efficiency
* Some flexibility of granularity: sharing is done at the Unit level but only one specific XBlock within an external unit can be used, effectively allowing sharing at the granularity of individual XBlocks or at the Unit level.
* Static assets are local to a Unit

The disadvantages are:
* Sharing of a Subsection or Section cannot be done, because Subsections are only defined by some XML within the `outline.xml` file of the course bundle, and that definition cannot be shared on its own (it's not an independent file/bundle/db-row)

**Comment by symbolist** [comment]
@ormsbee Nice! Yeah, we do need a more structured comparison next! One recommendation: I think we should add details somewhere about how each would be represented in database/storage (i.e. django models, manifest files structure, representation in url_name). Subtle changes to that can significantly impact different capabilities of the system and right now there is a lot of ambiguity about which variation is being proposed/discussed.

**Comment by bradenmacdonald** [comment]
Thanks @ormsbee! I filled this in and added one more :p

**Comment by symbolist** [comment]
@ormsbee @bradenmacdonald I am having a hard time understanding the differences between HOBC and the FOBC proposal in https://github.com/open-craft/blockstore/pull/27.

@ormsbee 

> One significant shortcoming of HOBC is that determining the entire course hierarchy/outline requires reading many different files from many different folders (read sections from course.json in the course folder, then read each section's section.xml from each section's folder, then read each subsection's subsection.xml from each subsection's folder, and so on...)

Hmm. Isn't this going to be the case for FOBC as well or is the structure stored somewhere in the BundleVersion?

**Comment by ormsbee** [comment]
Argh. Yes, definitely. I didn't write the HOBC entry, but I should have made note of it for FOBC (though I think all of them suffer from it to one degree or other depending on representation).

**Comment by symbolist** [comment]
@ormsbee @bradenmacdonald 

> though I think all of them suffer from it to one degree or other depending on representation

Isn't this equally the case for all of them? As far as I see there are three possible way of storing context graphs (course graphs, pathway graphs):

1. As a derived graph in Bundles alongside the context entities (like Courses and Pathways).
2. As a derived graph separately from Bundles which can be updated independently if we need to change its format.
3. As a M2M relationship or as a serialized list of identifiers in a Django field. As far as I see this is only possible in BPB. M2M relationship is not going to scale so we can leave that out. And if we were to go with a serialized list, we would need to do 2 anyway for efficiency.

What are the other possible options?

**Comment by symbolist** [comment]
@ormsbee @bradenmacdonald After sleeping on this for a few nights I am 👍on moving ahead with the HOBC/FOBC hierarchy. I agree it maps better to how courses are organized currently, developed top-down and with the import/export/transport features and is also the safer option in terms of resource requirements. Also I think at this point the 3 models have converged on a number of other attributes (at least as far as I understand them) and if needed the proposal in https://github.com/open-craft/blockstore/pull/27/files is flexible enough that we can de facto move towards smaller bundles; going in the other direction BPB > HOBC/FOBC is going to be much more complicated, if at all possible.

I am good with marking this issue as resolved to provide some closure for @ormsbee whenever you two are. :P

**Comment by ormsbee** [comment]
Decision: Broadly FOBC, detailed followup in #27

(Anyone who disagrees: Please feel free to re-open this issue.)

**Comment by bradenmacdonald** [comment]
Great, lets get this built :)
